### ISSUE TITLE
About the problem of tensor dimension mismatch

### ISSUE THREAD

**Issue by xuchenkai1** [mrwu-mac/ControlMLLM#1]
I configured the environment according to the instructions, and then an error occurred when running the demo code

![屏幕截图 2024-08-06 211628](https://github.com/user-attachments/assets/f1703afa-7b71-402c-86fc-87ed2a2963eb)
I want to know why this error occurs？

**Comment by mrwu-mac** [comment]
I can not get any useful information from this error. Do you able to run LLaVA inference successfully based on your configuration environment?

**Comment by mrwu-mac** [comment]
It seems to be an issue with the Transformers version. We have uploaded a new version of Transformers. Please try reinstalling Transformers. If the issue persists, please let us know, thank you.
