### ISSUE TITLE
get_local.cache is {'LlamaSdpaAttention.forward': []}  

### ISSUE THREAD

**Issue by spark-tom** [mrwu-mac/ControlMLLM#2]
@mrwu-mac Hello, when I run the `llava_roc.py`,  I got the below errors:

```
File "/controlmllm/task/ROC/llava_roc.py", line 217, in main
    mean_att = torch.cat([att.to(device) for att in attention_maps], 0).mean(0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors.
```

I find the line 212,
`ori_attention_maps = get_local.cache['LlamaSdpaAttention.forward'] `

get_local.cache['LlamaSdpaAttention.forward'] is empty([])

Can you give some suggestions? Thanks.

**Comment by mrwu-mac** [comment]
Hello, did you install the transformers from https://github.com/mrwu-mac/transformers? If you install the transformers from the official repository, you should ensure the following steps are completed. 

- First, the LLM attention in your model should be wrapped with the ```@get_local``` decorator from the visualizer to extract attention maps. For LLaVA_1.5, it should be in the ```LlamaSdpaAttention``` function in the ```transformers/src/transformers/models/llama/modeling_llama.py``` file.

- Second, in the ```llava_roc.py``` file, you should call ```get_local.activate()``` before importing your model. 

If these steps are followed correctly, the attention map will be stored as a dict in ```get_local.cache``` after the model inference. Please be mindful of the dict keys, as they may differ from those we provided. Please feel free to ask any questions if the issue persists.

**Comment by mrwu-mac** [comment]
In addition, in the ```LlamaSdpaAttention``` function, you need to obtain the ```attn_weights``` instead of the ```attn_output```, and make sure that the ```attn_weights``` are not reassigned within the forward function.

**Comment by spark-tom** [comment]
@mrwu-mac 
Thanks for your reply. I use  your latest code and your transformers library. I have check the items your listed above, it is consistent with your codes. The issue still exists.

**Comment by mrwu-mac** [comment]
I just tried the code we provided again with the reconfigured environment, and it works fine. Can you check if the value of ```attn_weights``` in the forward function of ```LlamaSdpaAttention``` is normal during model inference?

**Comment by spark-tom** [comment]
@mrwu-mac  Thanks for your reply.  I discovered that the reason was that my torch version was lower than 2.1.1, which does not support the sdpa mode in llama attention, and it supports eager mode by default. After updating my torch version,  it can work well.
