### ISSUE TITLE
About the optimization object

### ISSUE THREAD

**Issue by qizipeng** [mrwu-mac/ControlMLLM#3]
Hi, thanks for an wonderful work!

I have an question about the optimization object. It is seems that the optimized additional residual information can make the network pay more attention on the specify region. Why not directly or just optimize the input visual tokens? Why we need an additional learnable tokens? Can this way achieve a similar effect?

**Comment by mrwu-mac** [comment]
This question relates to code execution. We optimize additional learnable tokens for ease of execution, but essentially, this still optimizes the input visual tokens. We haven't attempted to directly optimize the input visual tokens, so we can't definitively say whether it would yield different results.
