### ISSUE TITLE
Exception: data did not match any variant of untagged enum ModelWrapper at line 277156 column 3

### ISSUE THREAD

**Issue by KaKa-101** [mrwu-mac/ControlMLLM#9]
Thanks for your great work.
But after installing the Transformers you preprocessed,  in the code line [`processor = AutoProcessor.from_pretrained(args.model_path)`](https://github.com/mrwu-mac/ControlMLLM/blob/a19cdeaff89fb52d72868c532c02c98c0f625936/task/ROC/llava_roc.py#L87)
I have encountered this problem:
![image](https://github.com/user-attachments/assets/6ab4e5c8-2184-40bf-b84d-3686bc0d8e26)
Could you tell me how to fix this problem? Thanks very much.

**Comment by mrwu-mac** [comment]
There could be two potential issues causing this problem:

1. Model weights might be corrupted: The most likely issue is that the model weight files might be corrupted. I recommend trying to redownload the model weights or using the official inference script to verify if the model files are working correctly.
	
2. Package version compatibility: If the model weights are not the issue, it might be related to the package version. Make sure you’re using a compatible version of the necessary packages. Updating or downgrading to a suitable version might resolve the problem.

**Comment by KaKa-101** [comment]
Thanks for your reply. I conducted `pip install --upgrade transformers` and the above question has been solved.
But in the code line https://github.com/mrwu-mac/ControlMLLM/blob/a19cdeaff89fb52d72868c532c02c98c0f625936/task/ROC/llava_roc.py#L128, I encounter this problem:
![image](https://github.com/user-attachments/assets/330975f3-7594-4d6b-a9ee-f038de937fa3)
So I print the `inputs`, it's like
![image](https://github.com/user-attachments/assets/0c0d0d56-51fe-47ce-ae16-02159d0f21f7)
The `32000` is expected to appear only 1 times, but here it appears 576 times. 
Could you tell me how to fix this problem?

**Comment by mrwu-mac** [comment]
Did you download the correct model weights? It seems that your padding_token_id has become 32000, but according to the LLAVA config file (https://huggingface.co/llava-hf/llava-1.5-7b-hf/blob/main/config.json), it should be 32001, as shown in the image below.
<img width="245" alt="截屏2024-12-16 10 27 59" src="https://github.com/user-attachments/assets/4993252f-8fa1-412f-a8d1-be011ba437bc" />

**Comment by mrwu-mac** [comment]
Sry, I misunderstood your question. Based on the description in the discussion (https://huggingface.co/llava-hf/llava-1.5-7b-hf/discussions/41), it seems that the latest commit of the model is incompatible with the environment. I recommend that you stick to the Transformer version I provided and try using an earlier version of the model weights (such as revision='a272c74' as mentioned in https://huggingface.co/llava-hf/llava-1.5-7b-hf/discussions/41) to resolve this issue.

**Comment by Hhankyangg** [comment]
I encountered the same issue and made the following modification:

```python
# processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")
processor = AutoProcessor.from_pretrained(
    'llava-hf/llava-1.5-7b-hf',
    revision='a272c74'
)
```

After the change, a new error occurred:

```shell
    prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)
AttributeError: 'LlavaProcessor' object has no attribute 'apply_chat_template'
```

This seems like a versioning issue. Do you have any suggestions for resolving this?

**Comment by KaKa-101** [comment]
> I encountered the same issue and made the following modification:
> 
> ```python
> # processor = AutoProcessor.from_pretrained("llava-hf/llava-1.5-7b-hf")
> processor = AutoProcessor.from_pretrained(
>     'llava-hf/llava-1.5-7b-hf',
>     revision='a272c74'
> )
> ```
> 
> After the change, a new error occurred:
> 
> ```shell
>     prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)
> AttributeError: 'LlavaProcessor' object has no attribute 'apply_chat_template'
> ```
> 
> This seems like a versioning issue. Do you have any suggestions for resolving this?

Hi, do you just add `revision='a272c74'` and make no other changes? I only change this line in the code:
```python
processor = AutoProcessor.from_pretrained(args.model_path,revision='a272c74')
```
But I still encounter the same issue:
```shell
fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum ModelWrapper at line 277156 column 3
```
Do you have other suggestions?

**Comment by mrwu-mac** [comment]
I haven’t tried a272c74 yet. Maybe you can try 05ae243. I found that a272c74 also seems to be a recently updated model.
